AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverless-cicd-test-function:
    Properties:
      AutoPublishAlias: Live
      CodeUri: s3://cashrewards.dev.bitbucket//ShopGoDev/serverless-cicd/master/deploy/b789d9fef0374b4a1a9144837475fea5
      DeploymentPreference:
        Alarms: null
        Type: Linear10PercentEvery1Minute
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
