AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverless-cicd-test-function:
    Properties:
      AutoPublishAlias: Live
      CodeUri: s3://cashrewards.dev.bitbucket//ShopGoDev/serverless-cicd/master/deploy//764d27bf20548c733d288d3fdf06c8d4
      DeploymentPreference:
        Alarms: null
        Type: Linear10PercentEvery1Minute
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
