AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  serverlesscicdtestfunction:
    Properties:
      AutoPublishAlias: Live
      CodeUri: s3://cashrewards.dev.bitbucket//ShopGoDev/serverless-cicd/master/deploy/ad6e83fb1c55298930d85e42b8485993
      DeploymentPreference:
        Alarms: null
        Type: Linear10PercentEvery1Minute
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
