AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mycicdstackTimeFunctionQQ8HEDFP1V63:
    Properties:
      AutoPublishAlias: Live
      CodeUri: s3://serverless-cicd-lxgzmy/4fbf86dfc51bae4379ea632a3f31f4c7
      DeploymentPreference:
        Alarms: null
        Type: Canary10Percent10Minutes
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
